#!/usr/bin/env python3
"""Attach/detach and advisory MOJO.md generation.

Mojo's default project integration is a reference layer. It creates local
metadata and a generated MOJO.md advisory file, but it does not mutate
human-authored instruction files such as AGENTS.md or CLAUDE.md.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Iterable

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from db_ops import DB_PATH, get_all_knowledge, get_db, init_db, knowledge_tier

console = Console()

MANIFEST_NAME = "mojo.json"
ADVISORY_FILE = "MOJO.md"
MOJO_START = "<!-- MOJO:ADVISORY:START - Generated by Mojo. Do not edit inside this block. -->"
MOJO_END = "<!-- MOJO:ADVISORY:END -->"


def _project_root(project_path: str | os.PathLike = ".") -> Path:
    return Path(project_path).expanduser().resolve()


def _manifest_path(project_path: str | os.PathLike = ".") -> Path:
    return _project_root(project_path) / ".mojo" / MANIFEST_NAME


def _read_manifest(project_path: str | os.PathLike = ".") -> dict | None:
    path = _manifest_path(project_path)
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def attach_project(project_path: str | os.PathLike = ".") -> dict:
    """Attach Mojo metadata to a project without creating a local DB."""
    init_db()
    root = _project_root(project_path)
    meta_dir = root / ".mojo"
    meta_dir.mkdir(parents=True, exist_ok=True)
    manifest = {
        "version": 1,
        "enabled": True,
        "project_path": str(root),
        "db_path": str(DB_PATH),
        "advisory_file": ADVISORY_FILE,
        "attached_at": datetime.now().isoformat(),
        "mode": "advisory",
    }
    _manifest_path(root).write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return manifest


def _remove_managed_mojo_md(root: Path) -> bool:
    path = root / ADVISORY_FILE
    if not path.exists():
        return False
    try:
        content = path.read_text(encoding="utf-8")
    except OSError:
        return False
    if MOJO_START not in content or MOJO_END not in content:
        return False
    path.unlink()
    return True


def detach_project(project_path: str | os.PathLike = ".") -> dict:
    """Disable project integration while preserving the central DB."""
    root = _project_root(project_path)
    meta_dir = root / ".mojo"
    manifest_path = _manifest_path(root)
    manifest = _read_manifest(root) or {
        "version": 1,
        "project_path": str(root),
        "db_path": str(DB_PATH),
        "advisory_file": ADVISORY_FILE,
        "mode": "advisory",
    }
    manifest["enabled"] = False
    manifest["detached_at"] = datetime.now().isoformat()
    meta_dir.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    removed_mojo_md = _remove_managed_mojo_md(root)
    return {**manifest, "removed_mojo_md": removed_mojo_md}


def project_status(project_path: str | os.PathLike = ".") -> dict:
    root = _project_root(project_path)
    manifest = _read_manifest(root)
    mojo_md = root / ADVISORY_FILE
    hooks_path = Path.home() / ".claude" / "settings.json"
    hooks_registered = False
    if hooks_path.exists():
        try:
            blob = hooks_path.read_text(encoding="utf-8").lower()
            hooks_registered = "on_session_end.py" in blob or "on_stop.py" in blob
        except OSError:
            hooks_registered = False
    return {
        "project_path": str(root),
        "attached": bool(manifest and manifest.get("enabled")),
        "manifest_path": str(_manifest_path(root)),
        "manifest_exists": bool(manifest),
        "db_path": str(DB_PATH),
        "db_exists": DB_PATH.exists(),
        "advisory_file": str(mojo_md),
        "advisory_exists": mojo_md.exists(),
        "mode": (manifest or {}).get("mode", "advisory"),
        "claude_settings": str(hooks_path),
        "claude_hooks_registered": hooks_registered,
    }


def _tokens(*parts: str) -> set[str]:
    text = " ".join(p for p in parts if p).lower()
    return {t for t in re.findall(r"[a-z0-9_./:-]+|[가-힣]+", text) if len(t) > 1}


def _path_domain_hints(file_paths: Iterable[str]) -> set[str]:
    hints: set[str] = set()
    for raw in file_paths:
        p = raw.lower()
        if any(x in p for x in ("test", "pytest", "spec")):
            hints.add("testing")
        if any(x in p for x in ("api", "router", "server", "fastapi")):
            hints.update({"web", "api", "fastapi"})
        if any(x in p for x in ("docker", "k8s", "deploy", "helm")):
            hints.update({"infra", "deployment"})
        if any(x in p for x in ("model", "train", "notebook", "sklearn")):
            hints.update({"ml", "data"})
        suffix = Path(p).suffix.lstrip(".")
        if suffix:
            hints.add(suffix)
    return hints


def _project_matches(item: dict, project_path: Path) -> bool:
    item_project = item.get("project_path") or ""
    if not item_project:
        return False
    try:
        saved = Path(item_project).expanduser().resolve()
    except OSError:
        return False
    return saved == project_path or project_path in saved.parents or saved in project_path.parents


def _score_item(item: dict, *, project_path: Path, task: str,
                file_paths: list[str]) -> tuple[float, list[str]]:
    reasons: list[str] = []
    if item.get("archived") or item.get("promotion_state") in {"rejected", "archived"}:
        return 0.0, reasons

    state = item.get("promotion_state", "candidate")
    score = {
        "generalized": 4.0,
        "project_approved": 3.5,
        "candidate": 1.6,
        "raw": 0.9,
    }.get(state, 1.0)
    reasons.append(f"{state.replace('_', ' ')} knowledge")

    if _project_matches(item, project_path):
        score += 3.0
        reasons.append("same project path")
    elif item.get("scope") in {"universal", "domain"}:
        score += 1.0
        reasons.append(f"{item.get('scope')} scope")
    elif item.get("scope") in {"environment", "workflow", "user_preference"}:
        score += 0.6
        reasons.append(f"{item.get('scope')} scope")

    query_terms = _tokens(task, " ".join(file_paths))
    item_terms = _tokens(
        item.get("title", ""),
        item.get("content", ""),
        item.get("reasoning", ""),
        item.get("applies_when", ""),
        item.get("does_not_apply_when", ""),
        item.get("domain", ""),
        " ".join(item.get("tags", []) or []),
    )
    overlap = sorted(query_terms & item_terms)
    if overlap:
        score += min(len(overlap), 5) * 0.7
        reasons.append("matched " + ", ".join(overlap[:5]))

    path_hints = _path_domain_hints(file_paths)
    domain_terms = set((item.get("domain") or "").split("/"))
    tag_terms = set(item.get("tags", []) or [])
    hint_overlap = sorted(path_hints & (domain_terms | tag_terms))
    if hint_overlap:
        score += min(len(hint_overlap), 3) * 0.5
        reasons.append("file context matched " + ", ".join(hint_overlap[:3]))

    if item.get("review_required"):
        score -= 0.25
        reasons.append("requires review")
    if item.get("conflicts_with"):
        score -= 0.2
        reasons.append("has conflicts")
    return max(score, 0.0), reasons


def retrieve_advisory_context(project_path: str | os.PathLike = ".",
                              task: str = "",
                              file_paths: list[str] | None = None,
                              limit: int = 8) -> list[dict]:
    """Return relevant knowledge with selection reasons and warnings."""
    init_db()
    root = _project_root(project_path)
    files = file_paths or []
    db = get_db()
    try:
        items = get_all_knowledge(db, min_confidence=0.0)
    finally:
        db.close()

    ranked = []
    for item in items:
        score, reasons = _score_item(
            item, project_path=root, task=task, file_paths=files
        )
        if score <= 0:
            continue
        ranked.append({
            **item,
            "tier": knowledge_tier(item),
            "_score": round(score, 3),
            "selected_because": reasons,
        })
    ranked.sort(key=lambda x: (x["_score"], x.get("updated_at", "")), reverse=True)
    return ranked[:limit]


def _lineage_label(item: dict) -> str:
    lineage = item.get("source_lineage") or {}
    if isinstance(lineage, str):
        try:
            lineage = json.loads(lineage)
        except json.JSONDecodeError:
            lineage = {"kind": "unknown", "ref": lineage}
    kind = lineage.get("kind", "unknown")
    ref = lineage.get("ref", "")
    return f"{kind}: {ref}" if ref else kind


def render_mojo_md(items: list[dict], project_path: str | os.PathLike = ".",
                   task: str = "", file_paths: list[str] | None = None) -> str:
    root = _project_root(project_path)
    files = file_paths or []
    lines = [
        MOJO_START,
        "# Mojo Advisory Context",
        "",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"Project: `{root}`",
        "",
        "This file is advisory context. Treat items as scoped guidance, not global instructions.",
        "Do not copy raw or candidate knowledge into AGENTS.md, CLAUDE.md, or SKILL.md without review.",
        "",
    ]
    if task:
        lines.append(f"Task: {task}")
    if files:
        lines.append("Files: " + ", ".join(f"`{f}`" for f in files))
    if task or files:
        lines.append("")

    if not items:
        lines.extend([
            "No relevant Mojo knowledge was selected for this context.",
            "",
            MOJO_END,
            "",
        ])
        return "\n".join(lines)

    for section_title, tier in (("Validated Tacit Knowledge", "T1"), ("Evidence And Candidates", "T2")):
        section_items = [i for i in items if i.get("tier") == tier]
        if not section_items:
            continue
        lines.append(f"## {section_title}")
        lines.append("")
        for item in section_items:
            lines.append(f"### {item['title']}")
            lines.append(
                f"- Scope: `{item.get('scope', 'project')}` | "
                f"Taxon: `{item.get('taxon', '')}` | "
                f"State: `{item.get('promotion_state', 'candidate')}` | "
                f"Evidence: `{item.get('evidence_level', 'raw_observation')}`"
            )
            if item.get("applies_when"):
                lines.append(f"- Applies when: {item['applies_when']}")
            if item.get("does_not_apply_when"):
                lines.append(f"- Does not apply when: {item['does_not_apply_when']}")
            if item.get("counterexamples"):
                lines.append("- Counterexamples: " + "; ".join(item["counterexamples"][:3]))
            if item.get("conflicts_with"):
                lines.append("- Conflicts with: " + ", ".join(item["conflicts_with"][:5]))
            if item.get("selected_because"):
                lines.append("- Selected because: " + "; ".join(item["selected_because"][:4]))
            lines.append(f"- Source: {_lineage_label(item)}")
            lines.append("")
            lines.append(item["content"].strip())
            if item.get("reasoning"):
                lines.append("")
                lines.append(f"Reasoning: {item['reasoning'].strip()}")
            lines.append("")

    lines.append(MOJO_END)
    lines.append("")
    return "\n".join(lines)


def refresh_project(project_path: str | os.PathLike = ".", task: str = "",
                    file_paths: list[str] | None = None,
                    limit: int = 8) -> tuple[Path, list[dict]]:
    root = _project_root(project_path)
    items = retrieve_advisory_context(root, task=task, file_paths=file_paths, limit=limit)
    content = render_mojo_md(items, root, task=task, file_paths=file_paths)
    out_path = root / ADVISORY_FILE
    out_path.write_text(content, encoding="utf-8")
    return out_path, items


def attach_main() -> int:
    parser = argparse.ArgumentParser(description="Attach Mojo advisory metadata to a project")
    parser.add_argument("--project", "-p", default=".", help="Project path")
    args = parser.parse_args()
    manifest = attach_project(args.project)
    console.print(
        f"[green]Attached Mojo advisory layer[/green] to [cyan]{manifest['project_path']}[/cyan]\n"
        f"[dim]Metadata: {_manifest_path(manifest['project_path'])}[/dim]\n"
        f"[dim]Knowledge DB: {manifest['db_path']}[/dim]"
    )
    return 0


def detach_main() -> int:
    parser = argparse.ArgumentParser(description="Detach Mojo advisory metadata from a project")
    parser.add_argument("--project", "-p", default=".", help="Project path")
    args = parser.parse_args()
    result = detach_project(args.project)
    removed = "removed generated MOJO.md" if result["removed_mojo_md"] else "left MOJO.md unchanged"
    console.print(
        f"[yellow]Detached Mojo advisory layer[/yellow] from [cyan]{result['project_path']}[/cyan]\n"
        f"[dim]{removed}; DB preserved at {result['db_path']}[/dim]"
    )
    return 0


def status_main() -> int:
    parser = argparse.ArgumentParser(description="Show Mojo project attachment status")
    parser.add_argument("--project", "-p", default=".", help="Project path")
    args = parser.parse_args()
    status = project_status(args.project)
    table = Table(title="Mojo Status")
    table.add_column("Field")
    table.add_column("Value")
    for key in (
        "project_path", "attached", "mode", "manifest_path",
        "db_path", "db_exists", "advisory_file", "advisory_exists",
        "claude_settings", "claude_hooks_registered",
    ):
        table.add_row(key, str(status[key]))
    console.print(table)
    return 0


def refresh_main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate project MOJO.md advisory context")
    parser.add_argument("--project", "-p", default=".", help="Project path")
    parser.add_argument("--task", "-t", default="", help="Current task or goal")
    parser.add_argument("--file", "-f", action="append", default=[], help="Relevant file path")
    parser.add_argument("--limit", type=int, default=8, help="Maximum knowledge items")
    args = parser.parse_args()
    out_path, items = refresh_project(
        args.project, task=args.task, file_paths=args.file, limit=args.limit
    )
    console.print(Panel.fit(
        f"[green]Generated[/green] {out_path}\n"
        f"Selected {len(items)} advisory item(s).\n"
        "No AGENTS.md, CLAUDE.md, or SKILL.md files were modified.",
        title="Mojo Refresh",
        border_style="green",
    ))
    return 0
