"""Sync knowledge to CLAUDE.md and Skills for Claude Code consumption."""

import os
import shutil
import sys
from collections import defaultdict
from pathlib import Path
from datetime import datetime

from rich.console import Console

sys.path.insert(0, str(Path(__file__).parent.parent))

from db_ops import evidence_based_grade, get_db, get_all_knowledge, get_stats, MOJO_DIR
from serve.packer import pack_knowledge, estimate_tokens

console = Console()

MOJO_START = "<!-- MOJO:START - Auto-managed by Mojo. Do not edit manually. -->"
MOJO_END = "<!-- MOJO:END -->"


def render_claude_md_section(items: list[dict]) -> str:
    """Render knowledge items as a CLAUDE.md section."""
    if not items:
        return ""

    lines = [
        "## Domain Knowledge (Mojo)",
        "",
    ]

    # Group by domain
    by_domain = defaultdict(list)
    for item in items:
        by_domain[item["domain"]].append(item)

    for domain in sorted(by_domain.keys()):
        domain_items = by_domain[domain]
        lines.append(f"### {domain}")

        for item in domain_items:
            # Compact format: grade + title + content + optional 1-line reasoning
            grade = evidence_based_grade(item)
            marker = "⚠️" if item["type"] == "anti_pattern" else "-"
            content = item["content"].replace("\n", " ").strip()
            line = f"{marker} [{grade}] **{item['title']}**: {content}"

            if item.get("reasoning"):
                # Compress reasoning to ~1 sentence
                reasoning = item["reasoning"].split(".")[0].strip() + "."
                line += f" ({reasoning})"

            lines.append(line)

        lines.append("")  # blank line between domains

    return "\n".join(lines)


def render_skill_md(domain: str, items: list[dict]) -> str:
    """Render a SKILL.md file for a domain."""
    # Create skill name from domain path
    skill_name = domain.replace("/", "-")
    
    # Build description
    tags = set()
    for item in items:
        tags.update(item.get("tags", [])[:3])
    tag_str = ", ".join(sorted(tags)[:10])

    lines = [
        "---",
        f"name: mojo-{skill_name}",
        f"description: Domain knowledge for {domain}. Auto-generated by Mojo. "
        f"Relevant for: {tag_str}.",
        "user-invocable: false",
        "---",
        "",
        f"# {domain} Domain Knowledge",
        f"",
        f"Auto-extracted from {len(items)} Claude Code sessions by Mojo.",
        f"Last updated: {datetime.now().strftime('%Y-%m-%d')}",
        "",
    ]

    # Group by type
    type_labels = {
        "domain_rule": "Rules",
        "architecture_decision": "Architecture Decisions",
        "anti_pattern": "Anti-Patterns (Avoid These)",
        "debug_playbook": "Debug Playbooks",
        "code_pattern": "Code Patterns",
        "tool_preference": "Tool Preferences",
    }

    by_type = defaultdict(list)
    for item in items:
        by_type[item["type"]].append(item)

    # Anti-patterns first (most important to not violate)
    type_order = ["anti_pattern", "domain_rule", "architecture_decision",
                  "debug_playbook", "code_pattern", "tool_preference"]

    for t in type_order:
        if t not in by_type:
            continue
        lines.append(f"## {type_labels.get(t, t)}")
        lines.append("")
        for item in by_type[t]:
            lines.append(f"### {item['title']}")
            lines.append(item["content"])
            if item.get("reasoning"):
                lines.append(f"*Why*: {item['reasoning']}")
            lines.append("")

    return "\n".join(lines)


def sync_claude_md(project_path: str, token_budget: int = 2000,
                   confidence_threshold: float = 0.5,
                   domain_priorities: dict = None):
    """Sync Mojo knowledge into project's CLAUDE.md."""
    db = get_db()
    all_knowledge = get_all_knowledge(db, min_confidence=confidence_threshold)
    db.close()

    # Exclude F-grade (deprecated) items from CLAUDE.md entirely
    all_knowledge = [k for k in all_knowledge if evidence_based_grade(k) != "F"]

    if not all_knowledge:
        console.print("[yellow]No knowledge to sync.[/yellow]")
        return

    # Pack within token budget
    packed = pack_knowledge(all_knowledge, token_budget, domain_priorities)

    if not packed:
        console.print("[yellow]No items fit within token budget.[/yellow]")
        return

    # Render Mojo section
    mojo_section = render_claude_md_section(packed)
    total_tokens = estimate_tokens(mojo_section)

    # Read existing CLAUDE.md
    claude_md_dir = Path(project_path) / ".claude"
    claude_md_dir.mkdir(parents=True, exist_ok=True)
    claude_md_path = claude_md_dir / "CLAUDE.md"

    existing = ""
    if claude_md_path.exists():
        existing = claude_md_path.read_text(encoding="utf-8")

    # Replace or append Mojo section
    if MOJO_START in existing and MOJO_END in existing:
        # Replace existing section
        before = existing[:existing.index(MOJO_START)]
        after = existing[existing.index(MOJO_END) + len(MOJO_END):]
        new_content = f"{before}{MOJO_START}\n{mojo_section}\n{MOJO_END}{after}"
    else:
        # Append
        separator = "\n\n" if existing.strip() else ""
        new_content = f"{existing}{separator}{MOJO_START}\n{mojo_section}\n{MOJO_END}\n"

    claude_md_path.write_text(new_content, encoding="utf-8")
    console.print(
        f"[green]✓ Synced {len(packed)} items to {claude_md_path} "
        f"(~{total_tokens} tokens)[/green]"
    )


def sync_skills(output_dir: str = None, skill_threshold: int = 10):
    """Generate SKILL.md files for domains with enough knowledge."""
    db = get_db()
    all_knowledge = get_all_knowledge(db, min_confidence=0.5)
    db.close()

    # Group by top-level domain
    by_domain = defaultdict(list)
    for item in all_knowledge:
        by_domain[item["domain"]].append(item)

    # Use default skills directory if not specified
    if output_dir is None:
        output_dir = str(MOJO_DIR / "skills")

    output_root = Path(output_dir)
    output_root.mkdir(parents=True, exist_ok=True)

    # Compute set of skills that should exist after this sync
    qualifying = {
        domain: items for domain, items in by_domain.items()
        if len(items) >= skill_threshold
    }
    wanted_names = {
        f"mojo-{domain.replace('/', '-')}" for domain in qualifying
    }

    # Remove stale Mojo-managed skill dirs no longer qualifying
    removed = 0
    for existing in output_root.glob("mojo-*"):
        if existing.is_dir() and existing.name not in wanted_names:
            shutil.rmtree(existing)
            console.print(f"[yellow]✗ Removed stale skill: {existing.name}[/yellow]")
            removed += 1

    generated = 0
    for domain, items in qualifying.items():
        skill_name = f"mojo-{domain.replace('/', '-')}"
        skill_dir = output_root / skill_name
        skill_dir.mkdir(parents=True, exist_ok=True)

        skill_content = render_skill_md(domain, items)
        skill_path = skill_dir / "SKILL.md"
        skill_path.write_text(skill_content, encoding="utf-8")

        console.print(f"[green]✓ Generated skill: {skill_name} ({len(items)} items)[/green]")
        generated += 1

    if generated == 0 and removed == 0:
        console.print(
            f"[dim]No domains have {skill_threshold}+ items. "
            f"Use --skill-threshold to lower.[/dim]"
        )


def main():
    """CLI entry point for sync."""
    import argparse
    parser = argparse.ArgumentParser(description="Sync Mojo knowledge")
    parser.add_argument("--project", default=".", help="Project path (default: cwd)")
    parser.add_argument("--budget", type=int, default=3000, help="Token budget")
    parser.add_argument("--confidence", type=float, default=0.5, help="Min confidence")
    parser.add_argument("--skill", action="store_true", help="Also generate Skills")
    parser.add_argument("--skill-threshold", type=int, default=10,
                        help="Min items to generate a Skill")
    args = parser.parse_args()

    project = os.path.abspath(args.project)
    sync_claude_md(project, token_budget=args.budget,
                   confidence_threshold=args.confidence)

    if args.skill:
        sync_skills(skill_threshold=args.skill_threshold)


if __name__ == "__main__":
    main()
